name: e2e tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      manual:
        description: "Trigger the workflow manually"
        required: false
  schedule:
    # CST is UTC-6, so 6:00 AM CST is 12:00 PM (or 12:00) UTC.
    # If daylight saving is in effect (CDT, UTC-5), this will run at 7:00 AM CDT.
    - cron: "0 12 * * *"

permissions:
  contents: read

jobs:
  build:
    name: e2e tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get current required Python version
        id: get-python-versions
        run: |
          MINIMUM_VERSION=$(grep -oP '__version_minimum_python__ = "\K.*(?=")' discbase/_version.py)
          echo "CURRENT_VERSION=$MINIMUM_VERSION" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.CURRENT_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make deps

      - name: Set environment variables
        run: |
          echo "E2E_BOT_TOKEN=${{ secrets.E2E_BOT_TOKEN }}" >> $GITHUB_ENV
          echo "E2E_CHANNEL_ID=${{ secrets.E2E_CHANNEL_ID }}" >> $GITHUB_ENV
        shell: bash

      - name: Run unit tests
        run: |
          make test-e2e
